name: Kevin Li
favicon: null
layout_spectrum: 0.047581283608451486
typography_spectrum: 0.028177585918456316
title: Digital Marketing in a difference perspective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe4e8'
    - '#797e81'
    - '#b5073c'
    - '#e8e10d'
    - '#ed881c'
  brandStrength: 0.8771689655259252
  lightness: 0.32421682216227055
  saturation: 0.6302691036835313
  rhythmicContrast: 0.7542102145962417
purpose: []
